config/routes.rb
Rails.application.routes.draw do
  root to: 'table_viewers#new'
  get '/table_viewer', to: 'table_viewers#new'
  resource :table_viewer, only: %w(create new show)
end

app/models/table_viewer.rb
class TableViewer

  attr_accessor :name, :table, :page

  def initialize(args)
    @page_inc = args[:page_inc] || 0
    @page = Integer(args[:page].empty? ? 0 : args[:page]) + Integer(@page_inc)
    @name = args[:name]
    @table = args[:table]
    url = "https://#{@name}.carto.com:443/api/v2/sql?q=select * from public.#{@table} LIMIT 25 OFFSET #{25 * @page + 1}"
    @response = TableViewer.fetch_json(url)
  end

  def fields
    @response["fields"].keys
  end

  def results
    @response["rows"]
  end

  def valid?
    @response.present? && @response["rows"].present?
  end

  private

  def self.fetch_json(url)
    uri = URI(url)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  rescue
    ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/table_viewers_controller.rb
class TableViewersController < ApplicationController
  before_action :set_table_viewer, only: %w(create)

  def new
  end

  def create
    flash[:error] = "Please make sure the user/table combo are available in carto :)" unless @table_viewer.valid?
    render 'show'
  end

  def show
  end

  private

  def table_viewer_params
    params.require(:table_viewer).permit(:name, :table, :page, :page_inc)
  end

  def set_table_viewer
    @table_viewer = TableViewer.new(table_viewer_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 'Carto Table Viewer'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      %div{class: "flash-#{key}"}= value

    #new_table_viewer
      %h1= 'Carto Table Viewer'
      #table_viewer_form
        = render 'form', html: {}, submit_text: 'load data', hidden: false, page_inc: 0

      = yield

app/views/table_viewers/_form.html.haml
= form_for :table_viewer, { url: table_viewer_path, method: :post }.merge(html) do |f|
  - if hidden
    = f.hidden_field :name
    = f.hidden_field :table
  - else
    = f.text_field :name
    = f.text_field :table
  = f.hidden_field :page
  - if page_inc != 0
    = f.hidden_field :page_inc, value: page_inc
  = f.submit(submit_text)

app/views/table_viewers/new.html.haml
%p="Go ahead and see your first table!"

app/views/table_viewers/show.html.haml
#table_viewer
- if @table_viewer && @table_viewer.valid?
  %table.tables
    %thead
      %tr
        - @table_viewer.fields.each do |f|
          %div
            %th= f
    %tbody
      - @table_viewer.results.each do |result|
        %tr
          - result.each do |k, v|
            %td= v

  #nav_links
    = render 'form', html: { html: { id: 'previous_button' } }, submit_text: 'previous', page_inc: -1, hidden: true
    = render 'form', html: { html: { id: 'next_button' } }, submit_text: 'next', page_inc: 1, hidden: true